### ISSUE TITLE
Error Unicode-3 

### ISSUE THREAD

**Issue by MarioAsti8** [delphi001/SAAMBE-3D#12]
Right after installing, I tried to run the following, to try if it worked properly:

```
python saambe-3d.py -i /home/mario/Desktop/standaloneCode/SAAMBE-3D-master/1a22.pdb -d 1 -o /home/mario/Desktop/SAAMBE_outputs/1a22.out -c A -r 182 -w C -m A

``` 

I got the following:

WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1700181129011/work/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
Traceback (most recent call last):
  File "/home/mario/Desktop/standaloneCode/SAAMBE-3D-master/saambe-3d.py", line 476, in <module>
    main()
  File "/home/mario/Desktop/standaloneCode/SAAMBE-3D-master/saambe-3d.py", line 461, in main
    pred = file_loop(
           ^^^^^^^^^^
  File "/home/mario/Desktop/standaloneCode/SAAMBE-3D-master/saambe-3d.py", line 316, in file_loop
    return pred_feature(label, model_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/Desktop/standaloneCode/SAAMBE-3D-master/saambe-3d.py", line 328, in pred_feature
    x = xgb.DMatrix(x)
        ^^^^^^^^^^^^^^
  File "/home/mario/miniconda3/envs/saambe3d/lib/python3.11/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/mario/miniconda3/envs/saambe3d/lib/python3.11/site-packages/xgboost/core.py", line 743, in __init__
    handle, feature_names, feature_types = dispatch_data_backend(
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/miniconda3/envs/saambe3d/lib/python3.11/site-packages/xgboost/data.py", line 962, in dispatch_data_backend
    return _from_numpy_array(data, missing, threads, feature_names, feature_types)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/miniconda3/envs/saambe3d/lib/python3.11/site-packages/xgboost/data.py", line 213, in _from_numpy_array
    _check_call(
  File "/home/mario/miniconda3/envs/saambe3d/lib/python3.11/site-packages/xgboost/core.py", line 279, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [17:13:56] /home/conda/feedstock_root/build_artifacts/xgboost-split_1700181129011/work/src/c_api/../data/array_interface.h:475: Unicode-3 is not supported.
Stack trace:
  [bt] (0) /home/mario/miniconda3/envs/saambe3d/lib/libxgboost.so(+0x20af61) [0x7f5cd0e0af61]
  [bt] (1) /home/mario/miniconda3/envs/saambe3d/lib/libxgboost.so(+0x22d12a) [0x7f5cd0e2d12a]
  [bt] (2) /home/mario/miniconda3/envs/saambe3d/lib/libxgboost.so(XGDMatrixCreateFromDense+0x186) [0x7f5cd0e2d9b6]
  [bt] (3) /home/mario/miniconda3/envs/saambe3d/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f5cddaff052]
  [bt] (4) /home/mario/miniconda3/envs/saambe3d/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f5cddafd925]
  [bt] (5) /home/mario/miniconda3/envs/saambe3d/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f5cddafe06e]
  [bt] (6) /home/mario/miniconda3/envs/saambe3d/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x92e4) [0x7f6117fe22e4]
  [bt] (7) /home/mario/miniconda3/envs/saambe3d/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x8836) [0x7f6117fe1836]
  [bt] (8) python(_PyObject_MakeTpCall+0x254) [0x502d54]

Looks like there is some issue with XGBoost and Unicode-3, I have XGBoost 1.7.6 installed. Any clue? Thanks.

**Comment by shaileshp51** [comment]
Hi Mario,
I just checked it, but was unable to reproduce the error you got. We are using Ubuntu 22.04 and have conda 23.11.0. I am also sharing the environment.yml, in case you want to cross check your conda environment. Can you freshly clone the repository and install the listed dependencies with listed version from conda-forge channel and give it a try again.

[environment.yml.txt](https://github.com/delphi001/SAAMBE-3D/files/13652309/environment.yml.txt)
